export const dotExplain = [
    "Sybil resistance based on decentralized pseudonymous biometric identities",
    "secure, scalable, efficient, consistent, immutable, and sustainable Substrate mechanism",
    "creation, proliferation, and development of a strong and dedicated community of human nodes",
    "custom low-latency high-throughput Sybil-resistant consensus protocol",
    "privacy-preserving biometric processing protocols",
    "distributed encrypted biometric templates matching",
    "ZK-proven liveness check",
    "EVM compatibility with the Substrate pallet",
    "native Humanode applications (wallets, etc.)",
    "biometric ownership;",
    "integration with EVM-compatible applications",
    "rich integration into Substrate ecosystem",
    "Humanode token (HMND) with Fath monetary system, equal fee distribution, and proportional emission distribution on the Humanode network",
    "Vortex, a DAO that regulates the existence of the Humanode network through voting",
    "a proposal system that pulls trending proposals to vote in Vortex",
    "Formation, a system that distributes grants across approved proposers and helps them to assemble a team to develop Humanode solutions",
    "a public Humanode knowledge base that stores all the information, research and analytics carried out by teams assembled in Formation. It will also act as a base in educational sessions and programs carried out in Humanode",
    "cryptobiometric applications that deliver proper flows in UX/UI",
    "multimodal biometrics",
    "ability to deploy Fath-based monetary systems",
    "ability to deploy your own tokens on Humanode with different monetary policies and systems",
    "Humanode development framework with modular solutions",
    "judicial system framework;",
    "BCIs for liveness detection",
    "neurosignatures for signing on-chain transactions",
    "internal modalities-based biometrics (neurosignatures, DNA matching)",
    "real-time proof-of-human-existence",
    "biometric-based Autonomous Intelligent Agent",
    "ZK offchain commitment-based smart contracts",
]
